### ISSUE TITLE
Discover "editor" command

### ISSUE THREAD

**Issue by szepeviktor** [phly/keep-a-changelog#25]
Hello!

Please discover the `editor` command in PATH (e.g. in Debian-based systems)

Debian releases have for example a symlink: `/usr/bin/editor`

**Comment by weierophinney** [comment]
This should be in place already.

The `edit` command uses the value of the environment variable `EDITOR`, which is generally set at the global level for users, and overridden by individual users when a different binary is desired. On Debian-based systems, this typically uses whatever the alternatives system has setup for `/usr/bin/editor` (which will be either nano or vi, based on what is installed).

If the `EDITOR` env variable is not found, the package defaults to `vi` on unix-based systems and `notepad` on windows systems; you can override what is used by passing a value via the `--editor` option, or setting the `EDITOR` env variable: `export EDITOR=/usr/bin/nvm`.

**Comment by szepeviktor** [comment]
Thank you.
