### ISSUE TITLE
Cannot parse changelogs with version links

### ISSUE THREAD

**Issue by PVince81** [phly/keep-a-changelog#38]
### Code to reproduce the issue

1. Run `keep-a-changelog new`
1. Run `keep-a-changelog bump:bugfix`
1. Manually edit "CHANGELOG.md" and add brackets to the version 0.1.1
1. Add a line at the end of the file `[0.1.1]: https://github.com/org/repo/compare/v0.1.0...v0.1.1`
1. Run `keep-a-changelog bump:bugfix`

### Expected results

Next bugfix release added.

### Actual results

Error about "Unable to find any changelog entries in file"

When looking at https://keepachangelog.com/en/1.0.0/ you can see that the format does accomodate for having links at the bottom.

**Comment by weierophinney** [comment]
Resolved in version 2.1.0.
