### ISSUE TITLE
Consider supporting conventional commit specs

### ISSUE THREAD

**Issue by damianopetrungaro** [phly/keep-a-changelog#4]
Did you consider supporting and implementing [the conventional commit](https://conventionalcommits.org/) specs for keep-a-changelog?

It endorses using proper commit messages and has clear changelogs.
See an example of the benefit take a look at the [Angular commits](https://github.com/angular/angular/commits/master)

**Comment by weierophinney** [comment]
Conventional commit is _orthogonal_ to Keep A Changelog format; it's something done during commit/merge. The messages from those can certainly make their way into the changelog itself (and, I'd argue that the sections they go into would be based on the scope), but the practice is separate from the Keep A Changelog format.
