### ISSUE TITLE
Backticked content is not added to CHANGELOG.md

### ISSUE THREAD

**Issue by webimpress** [phly/keep-a-changelog#49]
I run the command:

```console
$ keep-a-changelog entry:fixed --pr=5 "`MyNamespace\MyClass` - fixes something"
```

and the entry in the changelog was as follows:

```md
### Fixed

- [#5](https://github.com/webimpress/my-package/pull/5)  - fixes something
```

so the whole backticked content is gone somewhere and there are two spaces now.

**Comment by webimpress** [comment]
I've just noted that if I do:
```console
$ keep-a-changelog entry:fixed --pr=5 "\`MyNamespace\MyClass\` - fixes something"
```

it works correctly.

So maybe the issue is system dependent? Anyway, I would expect that everything between quotes is inserted as-is into CHANGELOG file.

**Comment by weierophinney** [comment]
This is totally dependent on your shell. Many shells interpret backticks within double quotes the same way PHP does, and spawn a system call with the contents (equivalent to `keep-a-changelog entry:fixed --pr=5 "$(MyNamespace\MyClass) - fixes something"`). If you use single quotes, you'll likely see this go away (I tend to use single quotes when writing my entries, and do not hit the problem — at least, not in zsh).
