### ISSUE TITLE
Command `release` with global configuration

### ISSUE THREAD

**Issue by webimpress** [phly/keep-a-changelog#50]
I have created global configuration with token. I was expected that it will be used on release, but I have to do it manually and I think the message is not clear that I can use global configuration.

What I would suggest is to have fallback to global configuration if there is no local configuration or at least change the error message to suggest maybe using global configuration if provided. Now we have:

```console
$ keep-a-changelog release webimpress/my-package 1.0.0
No token provided, and could not find it in the config file /home/Code/my-package/.keep-a-changelog.ini
Please provide the --token option, or create the config file with the config command
```

**Comment by weierophinney** [comment]
Configuation is completely revamped for version 2.0.0. If a token is specified for the requested provider within the global configuration, it will be used — unless you specify a different one via the `--provider-token` option.

Tokens are no longer allowed in local configuration, as it is too easy to check it in to your repository by accident, and file permissions are not secure.
