### ISSUE TITLE
Omit version when tagging/releasing

### ISSUE THREAD

**Issue by rieschl** [phly/keep-a-changelog#84]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Summary

It would be nice if the commands `verison:tag` and `version:release` didn't require the version but use the latest verison of the changelog, instead. And additionally an input question would be cool ("Version to tag/release. Default: 1.2.3").

**Comment by weierophinney** [comment]
Fixed with #92
